- name: install pip
  apt:
    name: python3-pip
    state: present

- name: pip install docker-py
  pip:
    name:
      - docker
      - docker-compose

- name: run container
  become: yes
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports: 8081:8080
    state: started
    pull: yes
  register: result
  retries: 5
  delay: 3
  until: result is succeeded

